// Generated by CoffeeScript 1.6.2
(function() {
  var gm,
    _this = this;

  gm = require("gm");

  gm("files/5160bd4c5a97fd6623000001.jpg").thumb(100, 100, "files/5160bd4c5a97fd6623000001.thumb.jpg", 90, function(err, sout, serr, cmd) {
    return err;
  });

}).call(this);
